/**********************************************************************

	--- Qt Architect generated file ---

	File: CDDBSetupData.h
	Last generated: Fri May 15 11:56:32 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CDDBSetupData_included
#define CDDBSetupData_included

#include <qwidget.h>


class KURLRequester;
class QCheckBox;
class QPushButton;
class QListBox;
class QLineEdit;

class CDDBSetupData : public QWidget
{
    Q_OBJECT

public:

    CDDBSetupData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CDDBSetupData();

public slots:


protected slots:

    virtual void enable_remote_cddb(bool);
    virtual void http_access_toggled(bool);

protected:
    KURLRequester* basedir_edit;
    QListBox* server_listbox;
    QPushButton* update_button;
    /* edm new section */
    QCheckBox* enable_auto_save_cddb;
    /* edm new section end */
    
    QCheckBox* remote_cddb_cb;
    QLineEdit* cddb_timeout_ef;
    QPushButton* defaults_button;
    QPushButton* help_button;
    QCheckBox* cddb_http_cb;
    QLineEdit* proxy_port_ef;
    QLineEdit* proxy_host_ef;
    QListBox* submission_listbox;

    QLineEdit *currentServerLE;
    QPushButton *currentServerAddPB;
    QPushButton *currentServerDelPB;

    QLineEdit *currentSubmitLE;
    QPushButton *currentSubmitAddPB;
    QPushButton *currentSubmitDelPB;
};

#endif // CDDBSetupData_included
