/**********************************************************************

	--- Dlgedit generated file ---

	File: CDDialogData.h
	Last generated: Thu Jan 1 15:56:19 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef CDDialogData_included
#define CDDialogData_included

#include <kdialogbase.h>

class QLabel;
class QLineEdit;
class QListView;
class QPushButton;

class CDDialogData : public KDialogBase
{
    Q_OBJECT

public:

    CDDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CDDialogData();

protected slots:


protected:
    QListView* tracksList;
    QLineEdit* trackEdit;   // track title edit
    QLineEdit* progseq_edit;// sequence of tracks for this disc edit
    QLineEdit* titleEdit;   // disc title edit
    QLineEdit* artistEdit;  // disc artist name edit
    QPushButton* ok_button;
    QPushButton* upload_button;
    QPushButton* load_button;
    QPushButton* cancel_button;
    QPushButton* ext_info_title_button;
    QPushButton* ext_info_button;
    QLabel* disc_id_label;
    QLabel* total_time_label;
};

#endif // CDDialogData_included
