
/* This header file was automatically generated by the kscd
   installation script. In case of trouble please edit
   config.h.std in the source directory of the kscd distribution
   and rename it to config.h .*/

#ifdef linux 

#ifndef DEFAULT_CD_DEVICE
  #define DEFAULT_CD_DEVICE   "/dev/cdrom"
#endif

#ifndef LINUX_SCSI_PASSTHROUGH
  #define LINUX_SCSI_PASSTHROUGH 
#endif

#ifndef MIN_VOLUME
  #define MIN_VOLUME 0
#endif

#ifndef MAX_VOLUME
  #define MAX_VOLUME 255
#endif

#endif /* linux */
