
/* This header file was automatically generated by the kscd
   installation script. In case of trouble please edit
   config.h.std in the source directory of the kscd distribution
   and rename it to config.h .*/

#ifdef linux 

#define DEFAULT_CD_DEVICE   "/dev/cdrom"  
#define LINUX_SCSI_PASSTHROUGH 
#define MIN_VOLUME 0 
#define MAX_VOLUME 255 

#endif /* linux */
